bases2fastq v4 - initial port

diff --git a/applications/bases2fastq/template.yaml b/applications/bases2fastq/template.yaml
--- a/applications/bases2fastq/template.yaml
+++ b/applications/bases2fastq/template.yaml
@@ -4,45 +4,55 @@
 {{- $scratch_mount := "/scratch" }}
 
 {{- /* assume input and output is local and fix otherwise */}}
-{{- $aws := false}}
-{{- $bases_http := false }}
+{{- $input_is := "local" }}
+{{- $output_is := "local" }}
 
 {{- $bases := printf "%s/%s/%s" $data_mount (trim .InputPath) (trim .RunName) }}
 {{- if (hasPrefix "s3://" (trim .InputPath)) }}
   {{- $bases = printf "%s/%s" (trim .InputPath) (trim .RunName) }}
-  {{- $aws = true }}
+  {{- $input_is = "s3" }}
 {{- end }}
 {{- if (or (hasPrefix "https://" (trim .InputPath)) (hasPrefix "http://" (trim .InputPath))) }}
   {{- $bases = printf "%s/%s.tar.gz" (trim .InputPath) (trim .RunName) }}
-  {{- $bases_http = true }}
+  {{- $input_is = "http" }}
 {{- end }}
 
 {{- $fastq := printf "%s/%s/%s" $data_mount (trim .OutputPath) (trim .RunName) }}
 {{- if (hasPrefix "s3://" (trim .OutputPath)) }}
   {{- $fastq = printf "%s/%s" (trim .OutputPath) (trim .RunName) }}
-  {{- $aws = true }}
+  {{- $output_is = "s3" }}
 {{- end }}
 
-{{- if (or (hasPrefix "s3://" .InputPath) (hasPrefix "s3://" .OutputPath)) }}
+{{- $local := (or (eq $input_is "local") (eq $output_is "local")) }}
+{{- $s3 := (or (eq $input_is "s3") (eq $output_is "s3")) }}
+
+{{- if $s3 }}
   {{- if not .AWSAccessKeyIdSecret }}{{- fail "AWSAccessKeyIdSecret is required when using S3" }}{{- end }}
   {{- if not .AWSSecretAccessKeySecret }}{{- fail "AWSSecretAccessKeySecret is required when using S3" }}{{- end }}
   {{- if not .AWSRegion }}{{- fail "AWSRegion is required when using S3" }}{{- end }}
 {{- end }}
 
-version: v1
+{{- if (and (not (trim .DataVolumeName)) $local) }}
+  {{- fail "DataVolumeName is required when InputPath or OutputPath is a local path" }}
+{{- end }}
+
+version: v4
 volumes:
   scratch:
-    reference: {{ .ScratchVolume }}
-{{- if $bases_http }}
+    use: {{ .ScratchVolumeProvisioner }}
+{{- if (eq $input_is "http") }}
     ingress:
       - source:
           uri: {{ $bases }}
         destination:
           uri: file://{{ printf "%s.tar.gz" (trim .RunName) }}
 {{- end }}
-{{- if (trim .DataVolume) }}
+{{- if $local }}
   data:
-    reference: {{ .DataVolume }}
+    name: {{ .DataVolumeName }}
+    {{- if (trim .DataVolumeProvisioner) }}
+    use: {{ .DataVolumeProvisioner }}
+    {{- end }}
 {{- end }}
 jobs:
   bases2fastq:
@@ -58,13 +68,13 @@ jobs:
       timeout:
         execute: {{ .Timeout }}
     mounts:
-      scratch:
-        location: {{ $scratch_mount }}
-      data:
-        location: {{ $data_mount }}
+      {{ $scratch_mount }}: scratch
+      {{- if $local }}
+      {{ $data_mount }}: data
+      {{- end }}
     cwd: {{ $scratch_mount }}
     env:
-{{- if $aws }}
+{{- if $s3 }}
       - AWS_ACCESS_KEY_ID={{ trim .AWSAccessKeyIdSecret }}
       - AWS_SECRET_ACCESS_KEY={{ trim .AWSSecretAccessKeySecret }}
       - AWS_DEFAULT_REGION={{ trim .AWSRegion }}
@@ -73,29 +83,27 @@ jobs:
       - RUN_NAME={{ trim .RunName }}
       - BASES={{ $bases }}
       - FASTQ={{ $fastq }}
-    command:
-      - /bin/bash
-      - "-c"
-      - |
-        fail() {
-          printf "ERROR: %s\n" "$*"
-          exit 1
-        }
-        mkdir -p "$TMPDIR"
+    script: |
+      #!/bin/bash
+      fail() {
+        printf "ERROR: %s\n" "$*"
+        exit 1
+      }
+      mkdir -p "$TMPDIR"
 
-        # if the input file is a tar archive from http(s) unpack the downloaded file in scratch and point $BASES to that
-        if [[ "$BASES" =~ ^https?:// ]] ; then
-            _tmp="{{ $scratch_mount }}/$RUN_NAME".tar.gz
-            [[ -e  "$_tmp" ]] || fail "unable to find downloaded run folder archive"
-            mkdir "$RUN_NAME"
-            tar --strip-components 1 -C "$RUN_NAME" -xzf "$_tmp" || fail "unable to uncompress dowloaded run folder archive"
-            [[ -e "$RUN_NAME/RunParameters.json" ]] || fail "Downloaded archive does not look like a run folder"
-            BASES="{{ $scratch_mount }}/$RUN_NAME"
-        fi
+      # if the input file is a tar archive from http(s) unpack the downloaded file in scratch and point $BASES to that
+      if [[ "$BASES" =~ ^https?:// ]] ; then
+          _tmp="{{ $scratch_mount }}/$RUN_NAME".tar.gz
+          [[ -e  "$_tmp" ]] || fail "unable to find downloaded run folder archive"
+          mkdir "$RUN_NAME"
+          tar --strip-components 1 -C "$RUN_NAME" -xf "$_tmp" || fail "unable to uncompress downloaded run folder archive"
+          [[ -e "$RUN_NAME/RunParameters.json" ]] || fail "Downloaded archive does not look like a run folder"
+          BASES="{{ $scratch_mount }}/$RUN_NAME"
+      fi
 
-        # the local destination should not exist yet
-        if [[ -d "$FASTQ" ]] ; then
-            fail "'$FASTQ' already exists; This should not happen. Processing skipped, no files deleted. Resolve manually"
-        fi
+      # the local destination should not exist yet
+      if [[ -d "$FASTQ" ]] ; then
+          fail "'$FASTQ' already exists; This should not happen. Processing skipped, no files deleted. Resolve manually"
+      fi
 
-        bases2fastq --num-threads {{ .Cores }} "$BASES" "$FASTQ"
+      bases2fastq --num-threads {{ .Cores }} "$BASES" "$FASTQ"
