FUZZ-4937: lammps gpu fix (#74)
* Initial modification of the lammps template

* Fixing template and scripts for experiment 1 to be more robust

* Creating separate run script for lammps

* Fixing issues in scripts

* Fixed temporary URL for experiments

* Change one lammps script to bash

* Fixes lammps script and allows gpu model specification

* Allows allocation of nvidia and amd gpus

* Clarify inputs for stagein and stageout

* Fixing a bunch of lint

* Pull from more recent commit of example repo

* Adapting to new tutorial data repo layout

* Adapting to new tutorial data repo layout

* Removes superfluous quotes from values.yaml and uses consistent folding for multiline strings

* Migrating to inline lammps input files

* Updates example 2

* Second experiment adds a chown b/c of owner uid on some file systems

* Diagnostics for permission errors

* Diagnostics for permission errors

* reverting some diagnostic output

* I forgot that i can't call lmp twice in the same stage

* Updates remainer of the examples

* Fixes lint

* Fixes nanotube simulation length

* Adds missing exit in example stagein script

* Makes nanotube stagein scripts more portable and robust

* Explicitly sets`newton on` in breakable nanotube example for kokkos compatibility

* Fixes kokkos neigh setting to be compatible with newton on

* Implements copilot suggestions

* Modifies breakable nanotube sim to use shrink wrap box

* Points default ExperimentUrl to main prior to merging

* Adds S3 egress

* Enables expriment scripts ingressed from s3

* Reorganizes inputs to make running different experiments easier

* Clarifies doc for how experiment scripts are found

* Fixes NVRC -> NVCR

diff --git a/applications/lammps_gpu/template.yaml b/applications/lammps_gpu/template.yaml
--- a/applications/lammps_gpu/template.yaml
+++ b/applications/lammps_gpu/template.yaml
@@ -1,28 +1,116 @@
 # Copyright 2025 CIQ, Inc. All rights reserved.
 version: v1
+
+{{- $expurl := trim .ExperimentUrl }}
+{{- if not $expurl }}
+  {{- fail "ExperimentUrl is required" }}
+{{- end }}
+
+{{- $stagein := trim .StageinScript }}
+{{- if not $stagein }}
+  {{- fail "StageinScript is required" }}
+{{- end }}
+{{- $lammps := trim .LammpsScript }}
+{{- if not $lammps }}
+  {{- fail "LammpsScript is required" }}
+{{- end }}
+
+{{- $scratch_vol := default "volume://user/ephemeral" .ScratchVolume | trim }}
+{{- $scratch_mount := "/scratch" }}
+
+{{- $data_vol := trim .DataVolume }}
+{{- $data_mount := "/data" }}
+
+{{- $run := trim .RunName }}
+{{- if not $run }}
+  {{- fail "RunName is required" }}
+{{- end }}
+{{- $run_dir := printf "%s/%s" $scratch_mount $run }}
+{{- $output_path := trim .OutputPath }}
+{{- $out_dir := printf "%s/%s" $data_mount $output_path }}
+
+{{- $s3_bucket := trim .S3Bucket }}
+{{- $s3_secret := trim .S3Secret }}
+{{- $s3_ingress := hasPrefix "s3://" $expurl }}
+{{- if (and (or $s3_bucket $s3_ingress) (not $s3_secret)) }}
+  {{- fail "S3Secret is required when using S3 for ingress or egress" }}
+{{- end }}
+
+{{- $ts := now | unixEpoch }}
+{{- $tar_base := list $run $ts | join "-" }}
+
+{{- $gpu_vendor := .GPUVendor | trim | lower }}
+{{- if eq $gpu_vendor "nvidia" }}
+  {{- $gpu_vendor = "nvidia.com" }}
+{{- else if eq $gpu_vendor "amd" }}
+  {{- $gpu_vendor = "amd.com" }}
+{{- else }}
+  {{- fail "Currently supported GPU vendors: NVIDIA and AMD" }}
+{{- end }}
+
+defaults:
+  job:
+    mounts:
+      scratch:
+        location: "{{ $scratch_mount }}"
+
 volumes:
-  lammps-data-volume:
-    name: lammps-data-volume
-    reference: {{.Volume}}
+  scratch:
+    reference: {{ $scratch_vol }}
     ingress:
+      - destination:
+          uri: file://stagein
+        source:
+          uri: {{ $expurl }}/{{ $run }}/{{ $stagein }}
+{{- if $s3_ingress }}
+          secret: {{ $s3_secret }}
+{{- end }}
+      - destination:
+          uri: file://run_lammps
+        source:
+          uri: {{ $expurl }}/{{ $run }}/{{ $lammps }}
+{{- if $s3_ingress }}
+          secret: {{ $s3_secret }}
+{{- end }}
+{{- if $s3_bucket }}
+    egress:
       - source:
-          uri: {{.LammpsInputUrl}}
+          uri: file://{{ $tar_base }}.tar.gz
         destination:
-          uri: file://{{.LammpsInputFile}}
+          uri: s3://{{ $s3_bucket }}/{{ $output_path }}/{{ $tar_base }}.tar.gz
+          secret: {{ $s3_secret }}
+{{- end }}
+{{- if $data_vol }}
+  data:
+    reference: {{ $data_vol }}
+{{- end }}
+
 jobs:
-  run-lammps:
+  stagein:
+    script: |
+      #!/bin/sh
+      set -e
+      chmod +x "{{ $scratch_mount }}/stagein"
+      "{{ $scratch_mount }}/stagein" "{{ $run_dir }}"
+    image:
+      uri: docker://alpine:3.23.3
+    resource:
+      cpu:
+        cores: 1
+      memory:
+        size: 512MiB
+
+  lammps:
     image:
       uri: {{.LammpsContainerUri}}
-      secret: {{.DepotSecret}}
-    env:
-      - LAMMPS_INPUT_FILE_PATH=/data/{{.LammpsInputFile}}
-    command:
-      - /bin/sh
-      - '-c'
-      - >-
-        lmp -k on g {{.GPUs}} -sf kk -pk kokkos cuda/aware on neigh full comm device binsize 2.8 -var x 8 -var y 4 -var z 8
-        -in ${LAMMPS_INPUT_FILE_PATH}
-    cwd: /data
+    depends-on:
+      - name: stagein
+        status: FINISHED
+    script: |
+      #!/bin/sh
+      set -e
+      chmod +x "{{ $scratch_mount }}/run_lammps"
+      "{{ $scratch_mount }}/run_lammps" "{{ $run_dir }}" {{.GPUs}}
     resource:
       cpu:
         cores: {{.Cores}}
@@ -30,10 +118,43 @@ jobs:
       memory:
         size: {{.Memory}}
       devices:
-        nvidia.com/gpu: {{.GPUs}}
+        {{ $gpu_vendor }}/gpu: {{.GPUs}}
+{{- if (trim .GPUModel) }}
+      annotations:
+        {{ $gpu_vendor }}/gpu.model: {{.GPUModel}}
+{{- end }}
+    multinode:
+      implementation: {{.MpiFlavor}}
+      nodes: {{.Nodes}}
     policy:
       timeout:
         execute: {{.Timeout}}
+
+{{- if (or $s3_bucket $data_vol) }}
+  stageout:
+    script: |
+      #!/bin/sh
+      set -e
+      echo "${FB_WORKFLOW_ID}" > "{{ $run_dir }}/FB_WORKFLOW_ID"
+      cd "{{ $scratch_mount }}"
+      tar -czf "{{ $tar_base }}.tar.gz" "{{ $run }}"
+{{- if $data_vol }}
+      mkdir -p "{{ $out_dir }}"
+      cp "{{ $tar_base }}.tar.gz" "{{ $out_dir }}/{{ $tar_base }}.tar.gz"
+{{- end }}
+    image:
+      uri: docker://alpine:3.23.3
+{{- if $data_vol }}
     mounts:
-      lammps-data-volume:
-        location: /data
+      data:
+        location: {{ $data_mount }}
+{{- end }}
+    depends-on:
+      - name: lammps
+        status: FINISHED
+    resource:
+      cpu:
+        cores: 1
+      memory:
+        size: 512MiB
+{{- end }}
